/*
 * Smart Parking Slot Sensor — XIAO ESP32S3 Sense (TinyML)
 * =========================================================
 * Uses TensorFlow Lite Micro to run an on-device CNN that classifies
 * each camera frame as "available" or "occupied". This replaces the
 * unreliable brightness heuristic with a real image classifier.
 *
 * Model input : 96 × 96 grayscale (matches FRAMESIZE_96X96)
 * Model output: 2 classes — [available, occupied]
 * Model file  : model.h (generated by arduino/training/train_model.py)
 *
 * Required Libraries (Arduino IDE → Tools → Manage Libraries):
 *   - TensorFlowLite_ESP32  (search "TensorFlowLite_ESP32")
 *   - PubSubClient          (by Nick O'Leary)
 *   - ESP32 board package   (by Espressif)
 *
 * Arduino IDE Settings:
 *   Board : "XIAO_ESP32S3"
 *   PSRAM : "OPI PSRAM"   ← REQUIRED — TFLite model lives in PSRAM
 *   Port  : your COM port
 *
 * Workflow:
 *   1. Collect ~100 images per class (occupied / available)
 *   2. Run: python arduino/training/train_model.py
 *   3. Copy generated model.h into this folder
 *   4. Flash this sketch
 */

#include <WiFi.h>
#include <PubSubClient.h>
#include "esp_camera.h"

// TensorFlow Lite Micro
#include <TensorFlowLite_ESP32.h>
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"

// Trained model — replace placeholder with output from train_model.py
#include "model.h"

// ============================================================
// ⚙️  CONFIGURATION — update these
// ============================================================

const char* WIFI_SSID     = "Gaurav's Galaxy S22+";
const char* WIFI_PASSWORD = "jrtu8475";

// IP of PC running Mosquitto: cmd → ipconfig → IPv4 Address
const char* MQTT_SERVER   = "10.21.63.215";
const int   MQTT_PORT     = 1883;

// Slot ID must match an entry in server.js
const char* SLOT_ID       = "A1";

// Minimum confidence to flip state (0.0–1.0)
// Below this both classes are uncertain → keep previous state
const float CONFIDENCE_THRESHOLD = 0.70f;

// How often to run inference (ms)
const unsigned long CHECK_INTERVAL     = 3000;
// Force-publish even if status unchanged
const unsigned long HEARTBEAT_INTERVAL = 30000;

// ============================================================
// Camera pin mapping — XIAO ESP32S3 Sense (DO NOT CHANGE)
// ============================================================
#define PWDN_GPIO_NUM   -1
#define RESET_GPIO_NUM  -1
#define XCLK_GPIO_NUM   10
#define SIOD_GPIO_NUM   40
#define SIOC_GPIO_NUM   39
#define Y9_GPIO_NUM     48
#define Y8_GPIO_NUM     11
#define Y7_GPIO_NUM     12
#define Y6_GPIO_NUM     14
#define Y5_GPIO_NUM     16
#define Y4_GPIO_NUM     18
#define Y3_GPIO_NUM     17
#define Y2_GPIO_NUM     15
#define VSYNC_GPIO_NUM  38
#define HREF_GPIO_NUM   47
#define PCLK_GPIO_NUM   13

// ============================================================
// Model constants — must match train_model.py settings
// ============================================================
#define MODEL_WIDTH    96
#define MODEL_HEIGHT   96
#define CLASS_AVAILABLE 0
#define CLASS_OCCUPIED  1

// Tensor arena in PSRAM — 200 KB fits a small quantized CNN.
// If AllocateTensors() fails, increase this value.
#define TENSOR_ARENA_KB 200

// ============================================================
// Globals
// ============================================================
WiFiClient   espClient;
PubSubClient mqttClient(espClient);

// Inference result — defined here (global scope) so Arduino's
// auto-prototyping sees it before generating function prototypes.
struct Prediction {
  float available;
  float occupied;
  bool  valid;
};

// TFLite objects (static so they outlive initModel())
namespace {
  const tflite::Model*      tflModel    = nullptr;
  tflite::MicroInterpreter* interpreter = nullptr;
  uint8_t*                  tensorArena = nullptr;
}

String        lastStatus    = "";
unsigned long lastCheckTime  = 0;
unsigned long lastPublishTime = 0;
bool cameraReady = false;
bool modelReady  = false;

// ============================================================
// WiFi
// ============================================================
void connectWiFi() {
  Serial.printf("WiFi: connecting to %s ...", WIFI_SSID);
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

  int tries = 0;
  while (WiFi.status() != WL_CONNECTED && tries < 40) {
    delay(500);
    Serial.print(".");
    tries++;
  }

  if (WiFi.status() == WL_CONNECTED) {
    Serial.printf(" connected (%s)\n", WiFi.localIP().toString().c_str());
  } else {
    Serial.println(" FAILED — restarting");
    delay(3000);
    ESP.restart();
  }
}

// ============================================================
// MQTT
// ============================================================
void connectMQTT() {
  while (!mqttClient.connected()) {
    String id = "XIAO-" + String(SLOT_ID);
    Serial.printf("MQTT: connecting as %s ...", id.c_str());

    if (mqttClient.connect(id.c_str())) {
      Serial.println(" connected");
      // Birth message so server knows the sensor is online
      mqttClient.publish(("parking/status/" + String(SLOT_ID)).c_str(), "online", true);
    } else {
      Serial.printf(" failed (rc=%d) — retry in 5s\n", mqttClient.state());
      delay(5000);
    }
  }
}

// ============================================================
// Camera — grayscale 96×96 to match model input exactly
// ============================================================
bool initCamera() {
  Serial.println("Camera: initializing...");

  if (!psramFound()) {
    Serial.println("Camera: ERROR — PSRAM not found.");
    Serial.println("  → In Arduino IDE: Tools → PSRAM → 'OPI PSRAM', then re-upload.");
    return false;
  }

  camera_config_t cfg = {};
  cfg.ledc_channel  = LEDC_CHANNEL_0;
  cfg.ledc_timer    = LEDC_TIMER_0;
  cfg.pin_d0        = Y2_GPIO_NUM;
  cfg.pin_d1        = Y3_GPIO_NUM;
  cfg.pin_d2        = Y4_GPIO_NUM;
  cfg.pin_d3        = Y5_GPIO_NUM;
  cfg.pin_d4        = Y6_GPIO_NUM;
  cfg.pin_d5        = Y7_GPIO_NUM;
  cfg.pin_d6        = Y8_GPIO_NUM;
  cfg.pin_d7        = Y9_GPIO_NUM;
  cfg.pin_xclk      = XCLK_GPIO_NUM;
  cfg.pin_pclk      = PCLK_GPIO_NUM;
  cfg.pin_vsync     = VSYNC_GPIO_NUM;
  cfg.pin_href      = HREF_GPIO_NUM;
  cfg.pin_sccb_sda  = SIOD_GPIO_NUM;
  cfg.pin_sccb_scl  = SIOC_GPIO_NUM;
  cfg.pin_pwdn      = PWDN_GPIO_NUM;
  cfg.pin_reset     = RESET_GPIO_NUM;
  cfg.xclk_freq_hz  = 20000000;
  cfg.pixel_format  = PIXFORMAT_GRAYSCALE;  // 1 byte/pixel, direct model input
  cfg.frame_size    = FRAMESIZE_96X96;      // exact model input size
  cfg.fb_count      = 1;
  cfg.fb_location   = CAMERA_FB_IN_PSRAM;
  cfg.grab_mode     = CAMERA_GRAB_LATEST;   // always get the newest frame

  esp_err_t err = esp_camera_init(&cfg);
  if (err != ESP_OK) {
    Serial.printf("Camera: init failed (0x%x)\n", err);
    Serial.println("  Fixes: re-seat camera ribbon, enable PSRAM, press reset.");
    return false;
  }

  Serial.println("Camera: ready (96x96 grayscale)");
  return true;
}

// ============================================================
// TFLite Micro — load model and allocate tensors
// ============================================================
bool initModel() {
  Serial.println("Model: loading...");

  // g_model and g_model_len are defined in model.h
  if (g_model_len == 0) {
    Serial.println("Model: ERROR — model.h is a placeholder.");
    Serial.println("  → Run: python arduino/training/train_model.py");
    Serial.println("  → Copy the generated model.h into this folder.");
    return false;
  }

  tflModel = tflite::GetModel(g_model);
  if (tflModel->version() != TFLITE_SCHEMA_VERSION) {
    Serial.printf("Model: schema mismatch (got %d, want %d)\n",
                  tflModel->version(), TFLITE_SCHEMA_VERSION);
    return false;
  }

  // Allocate tensor arena from PSRAM
  size_t arenaBytes = TENSOR_ARENA_KB * 1024;
  tensorArena = (uint8_t*)heap_caps_malloc(arenaBytes, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
  if (!tensorArena) {
    Serial.println("Model: ERROR — failed to allocate tensor arena in PSRAM.");
    return false;
  }

  // AllOpsResolver includes every built-in op — convenient but uses ~30KB more flash.
  // Once your model is final, switch to MicroMutableOpResolver and add only needed ops.
  static tflite::AllOpsResolver resolver;
  static tflite::MicroInterpreter static_interp(
      tflModel, resolver, tensorArena, arenaBytes, nullptr);
  interpreter = &static_interp;

  if (interpreter->AllocateTensors() != kTfLiteOk) {
    Serial.println("Model: AllocateTensors() failed.");
    Serial.printf("  → Try increasing TENSOR_ARENA_KB (currently %d KB)\n", TENSOR_ARENA_KB);
    return false;
  }

  // Log tensor shapes for debugging
  TfLiteTensor* in  = interpreter->input(0);
  TfLiteTensor* out = interpreter->output(0);
  Serial.printf("Model: loaded  arena used = %u bytes\n", interpreter->arena_used_bytes());
  Serial.printf("  input  shape: [%d, %d, %d, %d]  type: %d\n",
    in->dims->data[0], in->dims->data[1], in->dims->data[2], in->dims->data[3], in->type);
  Serial.printf("  output shape: [%d, %d]  type: %d\n",
    out->dims->data[0], out->dims->data[1], out->type);

  return true;
}

// ============================================================
// Preprocessing — copy camera frame into TFLite input tensor
//
// Handles both:
//   kTfLiteFloat32 — normalize pixels to [-1.0, 1.0]
//   kTfLiteInt8    — shift pixels from [0,255] to [-128,127]
//   kTfLiteUInt8   — copy raw pixel bytes directly
// ============================================================
void fillInputTensor(camera_fb_t* fb) {
  TfLiteTensor* in = interpreter->input(0);
  const int pixels = MODEL_WIDTH * MODEL_HEIGHT;  // 9216

  switch (in->type) {
    case kTfLiteFloat32:
      for (int i = 0; i < pixels; i++) {
        in->data.f[i] = (fb->buf[i] / 127.5f) - 1.0f;  // [0,255] → [-1,1]
      }
      break;

    case kTfLiteInt8:
      for (int i = 0; i < pixels; i++) {
        in->data.int8[i] = (int8_t)(fb->buf[i] - 128);  // [0,255] → [-128,127]
      }
      break;

    case kTfLiteUInt8:
    default:
      memcpy(in->data.uint8, fb->buf, pixels);
      break;
  }
}

// ============================================================
// Capture frame, run inference, return confidences
// ============================================================
Prediction runInference() {
  camera_fb_t* fb = esp_camera_fb_get();
  if (!fb) {
    Serial.println("Camera: capture failed");
    return {0.0f, 0.0f, false};
  }

  fillInputTensor(fb);
  esp_camera_fb_return(fb);  // return buffer immediately after copy

  if (interpreter->Invoke() != kTfLiteOk) {
    Serial.println("Model: Invoke() failed");
    return {0.0f, 0.0f, false};
  }

  TfLiteTensor* out = interpreter->output(0);
  float conf_avail, conf_occ;

  switch (out->type) {
    case kTfLiteFloat32:
      conf_avail = out->data.f[CLASS_AVAILABLE];
      conf_occ   = out->data.f[CLASS_OCCUPIED];
      break;

    case kTfLiteInt8: {
      float scale = out->params.scale;
      int   zp    = out->params.zero_point;
      conf_avail  = (out->data.int8[CLASS_AVAILABLE] - zp) * scale;
      conf_occ    = (out->data.int8[CLASS_OCCUPIED]  - zp) * scale;
      break;
    }

    case kTfLiteUInt8:
    default: {
      float scale = out->params.scale;
      int   zp    = out->params.zero_point;
      conf_avail  = (out->data.uint8[CLASS_AVAILABLE] - zp) * scale;
      conf_occ    = (out->data.uint8[CLASS_OCCUPIED]  - zp) * scale;
      break;
    }
  }

  return {conf_avail, conf_occ, true};
}

// ============================================================
// MQTT publish
// ============================================================
void publishStatus(const String& status, const Prediction& p) {
  // Main topic: simple string — consumed by server.js
  String topic = "parking/slots/" + String(SLOT_ID);
  mqttClient.publish(topic.c_str(), status.c_str(), true);  // retained

  // Debug topic: full JSON with confidence — consumed by server.js debug logger
  String dbg = "parking/debug/" + String(SLOT_ID);
  String json = "{\"slot\":\"" + String(SLOT_ID) +
                "\",\"status\":\"" + status +
                "\",\"conf_available\":" + String(p.available, 3) +
                ",\"conf_occupied\":"    + String(p.occupied,  3) +
                ",\"confidence\":"       + String(status == "occupied" ? p.occupied : p.available, 3) +
                ",\"method\":\"tflite\"}";
  mqttClient.publish(dbg.c_str(), json.c_str());

  Serial.printf("[%s] %-9s  avail=%.2f  occ=%.2f\n",
                SLOT_ID, status.c_str(), p.available, p.occupied);

  lastStatus      = status;
  lastPublishTime = millis();
}

// ============================================================
// Setup
// ============================================================
void setup() {
  Serial.begin(115200);
  delay(1000);

  Serial.println();
  Serial.println("==============================================");
  Serial.println("  Smart Parking Sensor  [TinyML / TFLite]");
  Serial.printf ("  Slot: %s   Threshold: %.0f%%\n", SLOT_ID, CONFIDENCE_THRESHOLD * 100);
  Serial.println("==============================================");
  Serial.println();

  connectWiFi();
  mqttClient.setServer(MQTT_SERVER, MQTT_PORT);
  connectMQTT();

  cameraReady = initCamera();
  if (cameraReady) {
    modelReady = initModel();
  }

  Serial.println();
  Serial.println(modelReady ? "Ready — running TFLite inference" : "WARNING — model not loaded");
}

// ============================================================
// Loop
// ============================================================
void loop() {
  // Keep connections alive
  if (WiFi.status() != WL_CONNECTED) connectWiFi();
  if (!mqttClient.connected())        connectMQTT();
  mqttClient.loop();

  unsigned long now = millis();
  if (now - lastCheckTime < CHECK_INTERVAL) return;
  lastCheckTime = now;

  // Retry init if hardware wasn't ready at boot
  if (!cameraReady) { cameraReady = initCamera(); if (!cameraReady) return; }
  if (!modelReady)  { modelReady  = initModel();  if (!modelReady)  return; }

  // --- Run inference ---
  Prediction p = runInference();
  if (!p.valid) return;

  // Determine status from model output
  String newStatus;
  if (p.occupied >= CONFIDENCE_THRESHOLD) {
    newStatus = "occupied";
  } else if (p.available >= CONFIDENCE_THRESHOLD) {
    newStatus = "available";
  } else {
    // Both classes below threshold — uncertain. Hold previous state.
    Serial.printf("[%s] uncertain (avail=%.2f  occ=%.2f) — holding: %s\n",
                  SLOT_ID, p.available, p.occupied,
                  lastStatus.isEmpty() ? "available" : lastStatus.c_str());
    if (lastStatus.isEmpty()) lastStatus = "available";
    return;
  }

  bool changed   = (newStatus != lastStatus);
  bool heartbeat = (now - lastPublishTime >= HEARTBEAT_INTERVAL);

  if (changed || heartbeat) {
    publishStatus(newStatus, p);
    if (changed) {
      Serial.println(newStatus == "occupied" ? ">> Car detected!" : ">> Slot cleared!");
    }
  }
}
